In [1]:
#Задание 1

import numpy as np

# Задаем размерность матрицы A и вектора-столбца f
n = 3

# Генерируем случайную матрицу A размером n x n
A = np.random.rand(n, n)

# Генерируем случайный вектор-столбец f размером n x 1
f = np.random.rand(n, 1)

print("Матрица A:")
print(A)
print("Вектор-столбец f:")
print(f)

Матрица A:
[[0.86162004 0.73661032 0.40257264]
 [0.25442657 0.45150822 0.23838046]
 [0.94054241 0.72828874 0.33058007]]
Вектор-столбец f:
[[0.32705418]
 [0.60729725]
 [0.83802968]]


In [2]:
#Решение с использованием обратной матрицы A
# Проверяем, что матрица A не является вырожденной
if np.linalg.det(A) != 0:
    # Решаем систему линейных уравнений с использованием обратной матрицы A
    X = np.linalg.inv(A) @ f # @ - оператор умножения матриц
    print("Решение системы линейных уравнений с использованием обратной матрицы A:")
    print(X)
else:
    print("Матрица A является вырожденной, решение системы линейных уравнений невозможно.")

Решение системы линейных уравнений с использованием обратной матрицы A:
[[-1.20432525]
 [ 6.88839922]
 [-9.21409127]]


In [3]:
# Решение системы линейных уравнений с использованием правила Крамера
X = np.zeros((n, 1))
det_A = np.linalg.det(A)

for i in range(n):
    Ai = A.copy()
    Ai[:, i] = f.flatten()
    det_Ai = np.linalg.det(Ai)
    X[i] = det_Ai / det_A

print("Решение системы линейных уравнений с использованием правила Крамера:")
print(X)

Решение системы линейных уравнений с использованием правила Крамера:
[[-1.20432525]
 [ 6.88839922]
 [-9.21409127]]


In [4]:
# Решение системы линейных уравнений с помощью функции numpy.linalg.solve
X_numpy = np.linalg.solve(A, f)

print("Решение системы линейных уравнений с помощью функции numpy.linalg.solve:")
print(X_numpy)

# Сравнение решений
if np.allclose(X, X_numpy):
    print("Решения, полученные разными методами, совпадают.")
else:
    print("Решения, полученные разными методами, не совпадают.")

Решение системы линейных уравнений с помощью функции numpy.linalg.solve:
[[-1.20432525]
 [ 6.88839922]
 [-9.21409127]]
Решения, полученные разными методами, совпадают.


In [5]:
#Задание 2

import numpy as np

def gaussian_elimination(A, b):
    n = len(A)
    for i in range(n):
        # Выбор главного элемента в столбце
        max_row = i
        for j in range(i + 1, n):
            if abs(A[j, i]) > abs(A[max_row, i]):
                max_row = j
        A[[i, max_row]] = A[[max_row, i]]
        b[[i, max_row]] = b[[max_row, i]]
        
        # Преобразование матрицы
        for j in range(i + 1, n):
            ratio = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - ratio * A[i, i:]
            b[j] = b[j] - ratio * b[i]
    
    # Обратный ход метода Гаусса
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    
    return x

# Пример использования
A = np.array([[2, 1, -1], [1, -3, 2], [3, -1, -1]])
b = np.array([5, -2, 3])

x = gaussian_elimination(A, b)
print("Решение системы:", x)


Решение системы: [2.16666667 2.5        1.        ]


In [10]:
import numpy as np

# Генерация случайной матрицы A размерности 20x20
A = np.random.rand(20, 20)

# Генерация случайного вектора X
X = np.random.rand(20)

# Определение числа обусловленности матрицы A
cond_A = np.linalg.cond(A)

# Умножение матрицы A на константу
A_modified = A * 1000

# Вычисление вектора f = AX
f = np.dot(A, X)

# Решение системы линейных уравнений методом Гаусса
solution_gauss = np.linalg.solve(A, f)

# Решение системы линейных уравнений методом с выбором главного элемента
solution_pivot = np.linalg.solve(A_modified, f)

# Вычисление разницы между найденными решениями и известным вектором X
difference_gauss = np.linalg.norm(solution_gauss - X)
difference_pivot = np.linalg.norm(solution_pivot - X)

# Сравнение значений разницы
if difference_gauss < difference_pivot:
    result = "Метод Гаусса дал более точный результат."
else:
    result = "Метод с выбором главного элемента дал более точный результат."

result


'Метод Гаусса дал более точный результат.'